version: "2"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pascalw/unifi-controller/config
    mem_limit: 4096m
    restart: unless-stopped
